#!/usr/bin/env python3
"""The developers.html page (standard library only), generated by tools/build_legal.py from two committed sources:

  legal-sources/developer-figures.json  every figure, label and billing sentence on the page (the developer documents are not published, so only the figures are here; see that file's note)
  legal-sources/legal.md                the one sentence about the unpublished developer documents, quoted exactly from the Legal page text

Every figure sits in an element with a data-src="dev:<plan>.<field>" attribute naming where it comes from; tools/check_site.py fails if the page shows anything else.
"""
import os

import legal_lib as L
import legal_md


def developer_documents_sentence(cfg):
    md = open(os.path.join(L.ROOT, 'legal-sources', 'legal.md'), encoding='utf-8').read()
    _, expected = legal_md.convert(md, L.date_text(cfg))
    return next(e for e in expected if e.startswith('Developer documents ('))


def content(fig, cfg):
    e = L.esc
    label = e(fig['availability'])
    rows = []
    for p in fig['plans']:
        k = p['key']
        note = ('<br><span data-src="dev:%s.note">%s</span>' % (k, e(p['note']))) if p['note'] else ''
        rows.append(
            '<tr><td><strong>%s</strong>%s</td><td data-th="Monthly fee" data-src="dev:%s.monthlyFee">%s</td><td data-th="Requests per day" data-src="dev:%s.dailyRequests">%s</td>'
            '<td data-th="AI answers per month" data-src="dev:%s.monthlyAnswers">%s</td><td><span class="avail" data-label="developer">%s</span></td></tr>'
            % (e(p['name']), note, k, e(p['monthlyFee']), k, e(p['dailyRequests']), k, e(p['monthlyAnswers']), label))
    parts = [
        '<h1>Developer plans</h1>',
        '<p class="meta">The SailCoCo developer API and MCP server. No developer plan can be bought yet: every plan below is available at general availability.</p>',
        '<div class="plans-wrap"><table class="plans">',
        '<thead><tr><th>Plan</th><th>Monthly fee</th><th>Requests per day</th><th>AI answers per month</th><th>Availability</th></tr></thead>',
        '<tbody>', '\n'.join(rows), '</tbody></table></div>',
        '<p data-src="dev:billing.monthlyOnly">%s</p>' % e(fig['billing']['monthlyOnly']),
        '<p data-src="dev:billing.usageBased">%s</p>' % e(fig['billing']['usageBased']),
        '<p data-src="dev:sourcesLine">%s</p>' % e(fig['sourcesLine']),
        '<p><q data-src="legal:developer-documents">%s</q></p>' % e(developer_documents_sentence(cfg)),
    ]
    return '\n'.join(parts)
