"""The content of 404.html, the page a visitor sees for an address that matches no page (generated by build_legal.py, checked by check_site.py like every other page).

Every link is root-relative: the page is shown at whatever address was asked for, so a relative link such as terms.html would resolve against that address."""


def content():
    return ('<h1>Page not found</h1>\n'
            '<p>That address does not match a page on sailcoco.com. It may have moved, or the link may be mistyped.</p>\n'
            '<ul>\n'
            '<li><a href="/">SailCoCo home page</a></li>\n'
            '<li><a href="/developers">Developer plans</a></li>\n'
            '<li><a href="/terms">Terms of Service</a></li>\n'
            '<li><a href="/privacy">Privacy Policy</a></li>\n'
            '<li><a href="/legal">Legal information</a></li>\n'
            '</ul>\n'
            '<p>Questions: <a href="mailto:support@sailcoco.com">support@sailcoco.com</a></p>')
